app = "postgres-alpine"

[build]
  dockerfile = "Dockerfile"

[env]
  POSTGRES_USER = "postgres"
  POSTGRES_DB = "postgres"

[mounts]
  source = "pg_data"
  destination = "/var/lib/postgresql/data"

[http_service]
  internal_port = 5432
  force_https = false
